---

- name: Laravel Setup
  hosts: ubuntu
  tasks:
    - name: Copy Script to Ubuntu Slave  Local Server
      copy:
        src: want.sh
        dest: ~/want.sh
        mode: 0755

    - name: Setup Cron to Check Server Up-Time Every 12AM
      cron:
        name: "Execute Cron Every 12AM"
        minute: "0"
        hour: "0"
        job: "uptime >> ~/uptime.log"

    - name: Check Server Uptime
      command: uptime -p
      register: uptime_out

    - name: Print Out Server Up-Time in Play
      debug:
        var: uptime_out.stdout

    - name: Execute Laravel App Deployment Script
      shell: ~/want.sh
